import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)

def add_heading(text, styles):
    return Paragraph(f"<b>{text}</b>", styles["Heading2"])

def add_text(text, styles):
    return Paragraph(str(text), styles["BodyText"])

def add_bullet_list(items, styles):
    elements=[]
    if not items:
        return [Paragraph("None", styles["BodyText"])]
    for item in items:
        elements.append(Paragraph(f"• {item}", styles["BodyText"]))
    return elements

def add_cover_page(story, styles, result):

    story.append(
        Paragraph(
            "BluePrint-AI",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 0.15 * inch))

    story.append(
        Paragraph(
            "Software Architecture Report",
            styles["Heading1"]
        )
    )

    story.append(Spacer(1, 0.5 * inch))

    project = (
        result.get("problem_statement")
        or "Architecture Blueprint"
    )

    story.append(
        Paragraph(
            f"<b>Project</b><br/>{project}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            f"<b>Generated On</b><br/>{datetime.now().strftime('%d %B %Y %I:%M %p')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 0.2 * inch))

    story.append(
        Paragraph(
            "<b>Generated By</b><br/>BluePrint-AI Multi-Agent Framework",
            styles["BodyText"]
        )
    )

    story.append(PageBreak())

def add_page_number(canvas, doc):
    """
    Draw page number and footer on every page.
    """

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    page_num = canvas.getPageNumber()

    canvas.drawString(
        40,
        20,
        "Generated by BluePrint-AI"
    )

    canvas.drawRightString(
        550,
        20,
        f"Page {page_num}"
    )

    canvas.restoreState()

def create_pdf_report(result):
    buffer=io.BytesIO()
    doc=SimpleDocTemplate(buffer,rightMargin=40,leftMargin=40,topMargin=40,bottomMargin=40)
    styles=getSampleStyleSheet()
    styles["Title"].alignment=TA_CENTER
    story=[]

    add_cover_page(
    story,
    styles,
    result
    )

    story.append(add_heading("Problem Statement",styles))
    story.append(add_text(result.get("problem_statement") or "Not Available",styles))
    story.append(Spacer(1,0.25*inch))

    req=result.get("requirements",{}) if isinstance(result.get("requirements",{}),dict) else {}
    story.append(add_heading("Functional Requirements",styles))
    story.extend(add_bullet_list(req.get("functional_requirements",[]),styles))
    story.append(Spacer(1,0.15*inch))
    story.append(add_heading("Non Functional Requirements",styles))
    story.extend(add_bullet_list(req.get("non_functional_requirements",[]),styles))
    story.append(Spacer(1,0.3*inch))

    story.append(add_heading("Technology Stack",styles))
    data=[["Component","Selected Technology","Reason"]]
    tech=result.get("techstack",{}) if isinstance(result.get("techstack",{}),dict) else {}
    for item in tech.get("stack",[]):
        data.append([item.get("component",""),item.get("choice",""),item.get("justification","")])
    table = Table(
    data,
    colWidths=[1.6*inch,2*inch,3*inch],
    repeatRows=1
    )
    table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1F4E79")),
    ("TEXTCOLOR", (0,0), (-1,0), colors.white),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("BACKGROUND", (0,1), (-1,-1), colors.HexColor("#F9FAFB")),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("LEFTPADDING", (0,0), (-1,-1), 10),
    ("RIGHTPADDING", (0,0), (-1,-1), 10),
    ("TOPPADDING", (0,0), (-1,-1), 8),
    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
    story.append(table)
    story.append(Spacer(1,0.3*inch))

    arch=result.get("architecture",{}) if isinstance(result.get("architecture",{}),dict) else {}
    story.append(add_heading("Architecture",styles))
    if arch.get("design_description"):
        story.append(add_text(arch["design_description"],styles))
        story.append(Spacer(1,0.15*inch))
    comps=arch.get("components",[])
    if comps:
        cdata=[["Component","Responsibility"]]
        for c in comps:
            cdata.append([c.get("name",""),c.get("responsibility","")])
        ctable=Table(cdata,colWidths=[2.4*inch,4.1*inch], repeatRows=1)
        ctable.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#0B6E99")),
    ("TEXTCOLOR", (0,0), (-1,0), colors.white),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("BACKGROUND", (0,1), (-1,-1), colors.HexColor("#F9FAFB")),
    ("VALIGN", (0,0), (-1,-1), "TOP"),
    ("LEFTPADDING", (0,0), (-1,-1), 10),
    ("RIGHTPADDING", (0,0), (-1,-1), 10),
    ("TOPPADDING", (0,0), (-1,-1), 8),
    ("BOTTOMPADDING", (0,0), (-1,-1), 8),
    ]))
        story.append(ctable)
    story.append(Spacer(1,0.3*inch))

    story.append(add_heading("Architecture Trade-offs",styles))
    story.extend(add_bullet_list(arch.get("tradeoffs",[]),styles))
    story.append(Spacer(1,0.3*inch))

    story.append(add_heading("Critic Review",styles))
    critic=result.get("critic_verdict",{}) if isinstance(result.get("critic_verdict",{}),dict) else {}
    verdict=critic.get("verdict","UNKNOWN")
    color="green" if verdict=="APPROVE" else "red"
    story.append(Paragraph(f"<font color='{color}'><b>Status: {verdict}</b></font>",styles["BodyText"]))
    if critic.get("issues"):
        story.extend(add_bullet_list(critic["issues"],styles))
    else:
        story.append(add_text("No issues reported.",styles))

    story.append(Spacer(1,0.5*inch))
    story.append(Paragraph("<b>Generated automatically by BluePrint-AI</b>",styles["BodyText"]))

    doc.build(
    story,
    onFirstPage=add_page_number,
    onLaterPages=add_page_number
    )
    buffer.seek(0)
    return buffer
